name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Login to Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | \
          docker login --username AWS --password-stdin 201385813146.dkr.ecr.eu-north-1.amazonaws.com

      # 3️⃣ Build, tag, and push Docker image
      - name: Build, tag, and push image to Amazon ECR
        run: |
          # Build Docker image
          docker build -t mediplus:v1 .

          # Tag it for ECR
          docker tag mediplus:v1 201385813146.dkr.ecr.eu-north-1.amazonaws.com/mediplus:v1

          # Push to ECR
          docker push 201385813146.dkr.ecr.eu-north-1.amazonaws.com/mediplus:v1
